# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Android Dev CI

on:
  pull_request:
    branches: [test-ci, main, dev]
  push:
    branches: [test-ci, main, dev]

jobs:

  # Test job
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      # setup env
      - name: Set Up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # run unit tests
      - name: Unit Tests
        run: cd UnitTestB && ./gradlew testDebugUnitTest

      # unit test report
      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }}



#  lint:
#    name: Lint Check
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v1
#      - name: set up JDK 1.8
#        uses: actions/setup-java@v1
#        with:
#          java-version: 1.8
#      - name: Lint debug flavor
#        run: ./UnitTestB/gradlew lintDebug --stacktrace
#      - name: Lint results
#        uses: actions/upload-artifact@v1
#        with:
#          name: app
#          path: app/build/reports/lint-results-debug.html
#
#  apk:
#    name: Generate APK
#    runs-on: ubuntu-latest
#
#    steps:
#      # setup env
#      - uses: actions/checkout@v1
#      - name: Set Up JDK 1.8
#        uses: actions/setup-java@v1
#        with:
#          java-version: 1.8
#      # grant permission for gradlew
#      - name: Grant execute permission for gradlew
#        run: chmod +x UnitTestB/gradlew
#      # Build APK
#      - name: Build APK
#        run: ./UnitTestB/gradlew assemble
#      - name: Upload APK
#        uses: actions/upload-artifact@v1
#        with:
#          name: app
#          path: app/build/outputs/apk/release/app-debug.apk
