# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Android CI main

on:
  pull_request:
    branches:
      - 'test-ci'
  push:
    branches:
      - 'test-ci'

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set Up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

#      - name: Make gradlew executable
#        run: chmod +x ./gradlew
#
#      - name: Build with Gradle
#        run: ./gradlew build

      - name: Run Tests
        run: ./gradlew test

      - name: Unit Tests Results
        uses: actions/upload-artifact@v1
        with:
          name: unit-tests-results
          path: app/build/reports/tests/testDebugUnitTest/index.html

  lint:
    name: Lint Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Lint debug flavor
        run: ./gradlew lintDebug --stacktrace
      - name: Lint results
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/reports/lint-results-debug.html

  apk:
    name: Generate APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build debug APK
        run: ./gradlew assemble
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/release/app-debug.apk
