# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Android CI main

on:
  pull_request:
    branches:
      - 'test-ci'
  push:
    branches:
      - 'test-ci'

jobs:
  test:
    name: Run Unit Tests
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v1

      # setup env
      - name: Set Up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # grant permission for gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x UnitTestB/gradlew

#      # gradle build
#      - name: Build with Gradle
#        run: ./UnitTestB/gradlew build

      # run unit tests
      - name: Unit Tests
        run: ./UnitTestB/gradlew testDebugUnitTest

      # unit test results
      - name: Upload Test Reports Folder
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: unit-tests-reports
          path: app/build/test-results

  report:
    runs-on: ubuntu-latest
    needs: test # Run after test job
    if: ${{ always() }}
    steps:
      - name: Download Test Reports Folder
        uses: actions/download-artifact@v2
        with:
          name: reports

      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0



#  lint:
#    name: Lint Check
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v1
#      - name: set up JDK 1.8
#        uses: actions/setup-java@v1
#        with:
#          java-version: 1.8
#      - name: Lint debug flavor
#        run: ./UnitTestB/gradlew lintDebug --stacktrace
#      - name: Lint results
#        uses: actions/upload-artifact@v1
#        with:
#          name: app
#          path: app/build/reports/lint-results-debug.html
#
#  apk:
#    name: Generate APK
#    runs-on: ubuntu-latest
#
#    steps:
#      # setup env
#      - uses: actions/checkout@v1
#      - name: Set Up JDK 1.8
#        uses: actions/setup-java@v1
#        with:
#          java-version: 1.8
#      # grant permission for gradlew
#      - name: Grant execute permission for gradlew
#        run: chmod +x UnitTestB/gradlew
#      # Build APK
#      - name: Build APK
#        run: ./UnitTestB/gradlew assemble
#      - name: Upload APK
#        uses: actions/upload-artifact@v1
#        with:
#          name: app
#          path: app/build/outputs/apk/release/app-debug.apk
